# Generated by Django 3.2.9 on 2021-12-04 12:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_consumerprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumerProfile',
            new_name='DemoConsumerProfile',
        ),
    ]
